#!/bin/sh

# Adds startcinnamon-community to the Cinnamon session
if [ "$(grep startcinnamon-community /usr/bin/cinnamon-session)" = "" ]; then
    sed -i '/exec \/usr\/lib\/cinnamon-session\/cinnamon-session-binary/i . /usr/bin/startcinnamon-community' /usr/bin/cinnamon-session
fi
